// packages/ui/plugins/query-generator-2/src/internal/CodeMirror.svelte
<script lang="ts">
  import CodeMirror, {Editor} from 'codemirror'
  import "codemirror/addon/edit/matchbrackets"
  import "codemirror/lib/codemirror.css"
  import "codemirror-graphql/src/mode"
  import { afterUpdate, onMount } from 'svelte'

  export let code: string
  export let mode: 'graphql' | 'graphql-variables'
  export let height: number | 'auto'
  export let theme: string = 'default'
  export let showLineNumbers: boolean = true

  let root: HTMLElement
  let codeMirror: Editor

  onMount(() => {
    codeMirror = CodeMirror(
      (elt) => {
        root.innerHTML = ''
        root.appendChild(elt)
      },
      {
        lineNumbers: showLineNumbers,
        value: code,
        theme: theme,
        mode: mode,
        readOnly: 'nocursor',
        indentUnit: 4,
        matchBrackets: true,
        smartIndent: false,
        dragDrop: false,
        spellcheck: false,
      },
    )

    codeMirror.setSize('auto', height)
  })

  afterUpdate(() => {
    if (codeMirror) {
      codeMirror.setOption('theme', theme)
      codeMirror.setOption('lineNumbers', showLineNumbers)
      codeMirror.setOption('mode', mode)
      codeMirror.setValue(code)
      codeMirror.setSize('auto', height)
      codeMirror.refresh()
    }
  })
</script>

<template>
  <div bind:this={root} />
</template>

// packages/ui/plugins/query-generator/src/components/CodeMirror.vue
<template>
  <div ref="root" />
</template>

<script lang="ts">
import 'codemirror/lib/codemirror.css'

import CodeMirror, { Editor } from 'codemirror'
import 'codemirror-graphql/mode'
import 'codemirror-graphql/variables/mode'
import 'codemirror/addon/edit/matchbrackets'

import { defineComponent, PropType, ref } from 'vue'
import { GraphQLSchema } from 'graphql'

export default defineComponent({
  props: {
    schema: {
      type: [Object, null] as PropType<GraphQLSchema | undefined>,
      required: false,
      default: undefined,
    },
    code: {
      type: String,
      required: true,
    },
    mode: {
      type: String as PropType<'graphql' | 'graphql-variables'>,
      required: true,
    },
    height: {
      type: [String, Number] as PropType<'auto' | number>,
      default: 'auto',
    },
    theme: {
      type: String,
      default: 'default',
    },
    showLineNumbers: Boolean,
  },
  setup() {
    return {
      root: ref<HTMLElement | null>(null),
    }
  },
  data() {
    return {
      codeMirror: null as Editor | null,
    }
  },
  mounted() {
    this.codeMirror = CodeMirror(
      (elt) => {
        if (this.root) {
          this.root.innerHTML = ''
          this.root.appendChild(elt)
        }
      },
      {
        lineNumbers: this.$props.showLineNumbers,
        value: this.$props.code,
        theme: this.$props.theme,
        mode: this.$props.mode,
        readOnly: 'nocursor',
        indentUnit: 4,
        matchBrackets: true,
        smartIndent: false,
        dragDrop: false,
        spellcheck: false,
      },
    )

    this.codeMirror.setSize('auto', this.$props.height)
  },
  updated() {
    if (this.codeMirror) {
      this.codeMirror.setOption('theme', this.$props.theme)
      this.codeMirror.setOption('lineNumbers', this.$props.showLineNumbers)
      this.codeMirror.setOption('mode', this.$props.mode)
      this.codeMirror.setValue(this.$props.code)
      this.codeMirror.setSize('auto', this.$props.height)
      this.codeMirror.refresh()
    }
  },
})
</script>
